# Image de base officielle PostgreSQL
FROM postgres:latest

# ## Configuration de la base de données

# ### Variables d'environnement
# Définissent les identifiants de connexion à la base de données
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=root
ENV POSTGRES_DB=sparadrapHibernate

