version: '3.8'  # Version de Docker Compose

services:  # Définition des services

  postgres:  # Service PostgreSQL
    image: postgres:latest  # Utilise l'image officielle PostgreSQL
    container_name: postgres_container  # Nom du conteneur PostgreSQL
    ports:  # Mapping des ports
      - "5432:5432"  # Mappe le port 5432 du conteneur au port 5432 de l'hôte
    environment:  # Variables d'environnement
      POSTGRES_USER: postgres  # Nom d'utilisateur PostgreSQL
      POSTGRES_PASSWORD: root  # Mot de passe PostgreSQL
      POSTGRES_DB: sparadrapHibernate  # Nom de la base de données PostgreSQL
      PGHOST: host.docker.internal  # Adresse IP spéciale pour accéder à la base de données locale
      PGPORT: 5432  # Port de la base de données PostgreSQL locale

  pgadmin:  # Service pgAdmin
    image: dpage/pgadmin4:latest  # Utilise l'image Docker pgAdmin
    container_name: pgadmin_container  # Nom du conteneur pgAdmin
    ports:  # Ports exposés
      - "5050:5050"  # Mappe le port 5050 du conteneur au port 5050 de l'hôte
    environment:  # Variables d'environnement
      PGADMIN_DEFAULT_EMAIL: jseb23@gmail.com  # Adresse e-mail par défaut pour pgAdmin
      PGADMIN_DEFAULT_PASSWORD: root  # Mot de passe par défaut pour pgAdmin
    depends_on:  # Dépendances
      - postgres  # pgAdmin dépend de PostgreSQL

  app:  # Service pour votre application
    build:  # Construction de l'image à partir du Dockerfile
      context: .  # Utilise le répertoire courant
      dockerfile: Dockerfile  # Spécifie le Dockerfile à utiliser
    ports:  # Mapping des ports
      - "8080:8080"  # Mappe le port 8080 du conteneur au port 8080 de l'hôte
    environment:  # Variables d'environnement
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/sparadrapHibernate  # Utilisation de "host.docker.internal" pour se connecter à la base de données locale
      SPRING_DATASOURCE_USERNAME: postgres  # Nom d'utilisateur de la base de données
      SPRING_DATASOURCE_PASSWORD: root  # Mot de passe de la base de données
    depends_on:  # Dépendances
      - postgres  # Le service "app" dépend du service "postgres"

  frontend:  # Service pour le serveur HTTP Apache
    image: httpd:latest  # Utilisation de l'image Apache HTTP Server (httpd)
    ports:  # Ports exposés
      - "80:80"  # Redirige le port 80 du conteneur vers le port 80 de l'hôte
    volumes:  # Montage des volumes
      - ./src/main/resources/static:/usr/local/apache2/htdocs  # Montage du répertoire contenant les fichiers front-end dans le conteneur Apache
      - ./src/main/resources/images:/usr/local/apache2/htdocs/images
    depends_on:  # Dépendances
      - app  # Le service "frontend" dépend du service "app"
