# Utilisation de l'image officielle de pgAdmin
FROM dpage/pgadmin4:latest

# Copie des fichiers de configuration personnalisés s'ils sont nécessaires
# COPY pgadmin_custom_config.py /pgadmin4

# Variables d'environnement pour configurer pgAdmin
ENV PGADMIN_DEFAULT_EMAIL=jseb23@gmail.com
ENV PGADMIN_DEFAULT_PASSWORD=root
