package com.jseb23.NewPharmacie.SeleniumTest;// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import lombok.extern.slf4j.Slf4j;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;



@Slf4j
public class DefaultSuiteTest
{
          private WebDriver driver;
          private Map<String, Object> vars;
          JavascriptExecutor js;


          @Before
         public void setUp()
         {
           WebDriverManager.chromedriver().setup();
           ChromeOptions options = new ChromeOptions();
           options.addArguments("--no-sandbox");
           options.addArguments("--disable-dev-shm-usage");
           options.addArguments("--headless");

           driver = new ChromeDriver(options);

           log.error("WebDriver initialized: " + driver);
         }
  @After
  public void tearDown() {
    driver.quit();
  }


  @Test
  public void testinterfaceapplicationnewPharmacie() {
    driver.get("http://localhost:63342/NewPharmacie/styles/maPharmacie.html?_ijt=jsi4420u535jffs5k5omv1sn3b&_ij_reload=RELOAD_ON_SAVE");
    driver.manage().window().setSize(new Dimension(1173, 1000));
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("jseb");
    driver.findElement(By.id("motDePasse")).click();
    driver.findElement(By.id("motDePasse")).sendKeys("rooot");
    driver.findElement(By.id("valider")).click();
    assertThat(driver.switchTo().alert().getText(), is("Authentification échouée"));
    driver.findElement(By.id("inscription")).click();
    driver.findElement(By.id("retourOublie")).click();
    driver.findElement(By.id("retourConnexionActivation")).click();
    driver.findElement(By.linkText("Retour à la connexion")).click();
    driver.findElement(By.id("mdp")).click();
    driver.findElement(By.linkText("Retour à la connexion")).click();
  }
}
