# Utilisation de l'image officielle d'Apache HTTP Server
FROM httpd:latest

# Copier les fichiers statiques et les images dans le répertoire htdocs
COPY ./src/main/resources/static /usr/local/apache2/htdocs
COPY ./src/main/resources/images /usr/local/apache2/htdocs/images
