name: Java CI/CD avec Maven et Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Installation Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli

      - name: Construction avec Maven
        run: mvn -B verify --file pom.xml

      # Build et pousse l'image Docker de l'application

      - name: Connect to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: jseb23/my-application:tagname


  build_docker:
    runs-on: ubuntu-latest
    needs: build_maven
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli

      # Télécharge et lance les conteneurs Docker à partir de l'image poussée
      - name: Start Docker Compose
        run: |
          docker-compose --version
          docker-compose pull
          docker-compose up --force-recreate -d
          docker ps

      # Attendre quelques secondes pour permettre aux conteneurs de démarrer
      - name: Wait for containers to start
        run: sleep 10
