
name: Java CI/CD avec Maven et Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  build_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install google-chrome-stable
          google-chrome --version

      - name: Construction avec Maven
        run: mvn -B verify --file pom.xml

  build_docker:
    runs-on: ubuntu-latest
    needs: build_maven
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli

      - name: Start Docker Compose
        run: |
          docker-compose --version
          docker-compose up --force-recreate -d
          docker ps



