
name: Java CI/CD avec Maven et Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  build_maven:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run Chrome Browser
        run: chrome --version

      - name: Build with Maven
        run: mvn -B verify --file pom.xml

  build_docker:
    runs-on: ubuntu-latest
    needs: build_maven
    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose
        run: docker-compose up -d



